# Generated by Django 6.0.3 on 2026-03-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
