# Generated by Django 6.0.3 on 2026-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_is_approved_testimonial_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='updated_at',
        ),
    ]
